name: Update AFL Ladder

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-afl-ladder:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run AFL Ladder Scraper
        run: npm start

      - name: Commit and push changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Leon Stafford"
          git config user.email "me@ljs.dev"
          git config --global credential.helper cache
          git config --global credential.helper 'store --file=.git/credentials'
          echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > .git/credentials
          git add README.md afl-ladder.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update AFL ladder data"
          git push
